{% set name = "bravado" %}
{% set version = "10.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fd1bd1d24dd246846c931edfcd04617e83689a91dc6b415db28384568bf8961

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - bravado-core >=5.0.1
    - monotonic
    - msgpack-python
    - pip
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.4
    - six
  run:
    - bravado-core >=5.0.1
    - monotonic
    - msgpack-python
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.4
    - six

test:
  imports:
    - bravado
    - bravado.testing

about:
  home: https://github.com/Yelp/bravado
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for accessing Swagger-enabled API's

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
