{% set name = "bravado" %}
{% set version = "11.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bb6ef75d84140c851fffe6420baaee5037d840070cfe11d60913be6ab8e0530

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bravado-core >=5.16.1
    - monotonic
    - msgpack-python
    - python >=3.6
    - python-dateutil
    - pyyaml
    - requests >=2.17
    - simplejson
    - six
    - typing-extensions

test:
  imports:
    - bravado
    - bravado.testing

about:
  home: https://github.com/Yelp/bravado
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for accessing Swagger-enabled API's

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
