{% set name = "bravado" %}
{% set version = "10.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ce16cda070c421fe1a30893033cc96cb8ea13f6201615281e7b0d04fcea348a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - bravado-core >=5.0.1
    - monotonic
    - msgpack-python
    - pip
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.4
    - six
  run:
    - bravado-core >=5.0.1
    - monotonic
    - msgpack-python
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.4
    - six

test:
  imports:
    - bravado
    - bravado.testing

about:
  home: https://github.com/Yelp/bravado
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for accessing Swagger-enabled API's

extra:
  recipe-maintainers:
    - chapmanb
    - marcelotrevisani
