travis:
  secure:
    BINSTAR_TOKEN: rQDcuOw/tsEwsAF2sd9luVAeT1DIxtudcU34+IWcWEkGuKd4U5R1xNbx0eXHLseMDRXsj3gfpK+CFXeTDdgYnTN5sbQtWIRuu8Wn3JfzbOWGt/lT6xganpQSt15vtyoxGaYysvslnDS3fv8fg2Um5pvVSjnLGMvRFHIEvLPi7lfiZBKIVZDmrYGWCFMD2qFmENcbq0q2Al+yrqu1mGS5hb1WU9qNp0ZY3v94hvUFxV1ouAeR0NsoUPfaQMbo9zHaKQvFCkCs32AKYR2GkzH7iwiMMY2qpp1wg8Dx9HI4TN4n2PETXh976e0AOtd5G3ab1+NEAXkBezL/KH0xrr322wqHkTj8o04mi6KS57q9fjOGGYE2FaV12Vl5Prnw+2BLQjel83OBFkah0rnx5wJJSsgGQ7ED3QvzQieyfKWugxgCepn/K+6koepEjbL6FQ5xhOq0pzLllmKnDZNl9mUwzcX6o4CfVGPTTuSwLqvceJPpJBtQLvd6Etvgek2S6GthJ2ZlXYc2A4m1MpmB/1+qpYcQ1e6yr/toHGfaz8EX+jvbs3Y95X8bvXvrUHHpiAwjlOvdof8ah2CMBVrsc5T5ab/pOdyROtANIsiCCDwxqB33gps7PUbHxGQa7GadVSXCZZ7H0BjL8jd4ApZZ+aPeQPj07H0Np1Pp+nvjnlhT0lc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
